### ISSUE TITLE
Swing Mode detection

### ISSUE THREAD

**Issue by mkz212** [embee8/homebridge-panasonic-ac-platform#27]
Hi.

I have Panasonic CS-Z50VKEW. And Your code works well except for one thing - it reads the swing mode wrong.

But it works well when I change just one line in indoor-unit.js. First line in this part:

```js
// Swing Mode (optional)
if (deviceStatus.fanAutoMode === 0 || deviceStatus.fanAutoMode === 2 || deviceStatus.fanAutoMode === 3 ) {
    this.service.getCharacteristic(this.platform.Characteristic.SwingMode)
        .updateValue(this.platform.Characteristic.SwingMode.SWING_ENABLED);
}
else {
    this.service.getCharacteristic(this.platform.Characteristic.SwingMode)
        .updateValue(this.platform.Characteristic.SwingMode.SWING_DISABLED);
}
```

Maybe you need to enter the Swing mode selection in the configuration? Or based on the model?

Regards,
Michal

**Comment by embee8** [comment]
> [...] it reads the swing mode wrong.

Can you elaborate on this suggestion? In which cases is the swing mode not reported correctly?

Note that the [current implementation](https://github.com/embee8/homebridge-panasonic-ac-platform/blob/a8bdd2ea702707f6533e78451779b8f56957f736/src/accessories/indoor-unit.ts#L254) uses the `airSwingLR` and `airSwingUD` values to determine whether both swing modes are enabled. Apple/Homebridge only gives us a single toggle rather than separate ones for left-right and up-down.

This is why the current implementation uses the toggle to control the "full auto mode", i.e. when both are on auto. Same applies to the [outgoing device update](https://github.com/embee8/homebridge-panasonic-ac-platform/blob/a8bdd2ea702707f6533e78451779b8f56957f736/src/accessories/indoor-unit.ts#L356) - when the toggle is switched on, the plugin will enable both swings.

This approach is based on Cody's [homebridge-panasonic-air-conditioner plugin](https://github.com/codyc1515/homebridge-panasonic-air-conditioner).

Besides this, I'd be interested in the value range of `fanAutoMode` and what each value represents. A table, mapping each value to a state would be useful to determine whether this field is more accurate in reading the swing mode.

**Comment by mkz212** [comment]
I have Cody's plugin (same swing mode code). I tested it with different combinations. From what I remember, at some time Panasonic changed its api.

Yes i know that Panasonic Comfort Cloud App have two switches - for up/down swing and for left/right swing.
When I enable swing mode in Home App (one switch) it enables two switches in Panasonic Comfort Cloud and vice versa.

There is a "fanAutoMode" parameter setting command in your code, and therefore the code works fine as long as you don't change one swing mode in Panasonic Comfort Cloud app.

fanAutoMode:
1 - both enabled
2- both disabled
3 - up/down enabled and left/right disabled
4. - up/down disabled and left/right enabled

Changing that one line just makes Swing Mode work perfectly for me.

Regards,
Michal

**Comment by 1homebridge** [comment]
> I have Cody's plugin (same swing mode code). I tested it with different combinations. From what I remember, at some time Panasonic changed its api.
> 
> Yes i know that Panasonic Comfort Cloud App have two switches - for up/down swing and for left/right swing. When I enable swing mode in Home App (one switch) it enables two switches in Panasonic Comfort Cloud and vice versa.
> 
> There is a "fanAutoMode" parameter setting command in your code, and therefore the code works fine as long as you don't change one swing mode in Panasonic Comfort Cloud app.
> 
> fanAutoMode: 1 - both enabled 2- both disabled 3 - up/down enabled and left/right disabled 4. - up/down disabled and left/right enabled
> 
> Changing that one line just makes Swing Mode work perfectly for me.
> 
> Regards, Michal

Hi
Are you still able to use Cody’s Plug-in as it’s coming up with a “new version of the app is published” and the plug-in is now archived, meaning there will be no update to address this. 

Thanks

**Comment by mkz212** [comment]
No. I removed that plugin and now use this one.

**Comment by embee8** [comment]
>When I enable swing mode in Home App (one switch) it enables two switches in Panasonic Comfort Cloud and vice versa.

This is intended behaviour. The toggle in the Home app is supposed to activate both swings (LR + UD). Once you change the setting in the Panasonic app, the Home app will show the swing mode as disabled, which isn't quite true, but again on the basis off: both swing modes enabled = HomeKit swing mode enabled. To get both in sync again, simply switch off or on the toggle in the Home app.

>Changing that one line just makes Swing Mode work perfectly for me.

From your perspective, what would be the best representation of the various swing modes, if it doesn't align with what I described above?

**Comment by mkz212** [comment]
With Your code (and Cody’s code) changing swing mode from Panasonic app doesn’t change anything in my home app. It simply doesn’t work.

**Comment by embee8** [comment]
>It simply doesn’t work.

I get your point, but please refer to the last question of my previous comment in order to work out how we should deal with the fact that the Home app only has one swing mode toggle, and the Panasonic app has two.

In an attempt to clarify this, I am going to answer my own question and you let me know whether that sounds good to you.

| Panasonic app: UD auto swing mode | Panasonic app: UD auto swing mode | Home app swing mode |
| :-: | :-: | :-: |
| Off | Off | Off |
| Off | On | Off |
| On | Off | Off |
| On | On | On |

This means:
1) The Home app toggle will represent both swing modes being on auto
2) Switching off the toggle will deactivate both automatic swing modes
3) Switching on the toggle will activate both automatic swing modes
4) If the Home app toggle is on, and the user switches off one of the automatic modes in the Panasonic app, the Home app toggle will flip to off (also see point 1).

Let's align on this first, and then address the gaps in the current implementation if there are any.

**Comment by mkz212** [comment]
1. Enable swing in Home app - auto mode LR and UP (fanAutoMode: 1)
2. Disable swing in Home app - LR in center (airSwingLR: 2), UD in top (airSwingUD: 0)
3. If in Panasonic app any swing (LR or UD) is enabled then in home app swing is enabled
4. If in Panasonic app both swing are disabled then in home app swing is disabled.




All your code is OK! Just change this ONE line in this part of code in indoor-unit.js :
```
// Swing Mode (optional)
            if (deviceStatus.fanAutoMode === 0 || deviceStatus.fanAutoMode === 2 || deviceStatus.fanAutoMode === 3 ) {
                this.service.getCharacteristic(this.platform.Characteristic.SwingMode)
                    .updateValue(this.platform.Characteristic.SwingMode.SWING_ENABLED);
            }
            else {
                this.service.getCharacteristic(this.platform.Characteristic.SwingMode)
                    .updateValue(this.platform.Characteristic.SwingMode.SWING_DISABLED);
            }
```

**Comment by embee8** [comment]
That sounds like a reasonable approach. It's slightly different to what I suggested above but I like it because your proposal reflects reality a bit better, i.e. show swing mode as enabled in Home app if at least one swing mode (LR or UD) is enabled.

Though, in [this comment](https://github.com/embee8/homebridge-panasonic-ac-platform/issues/27#issuecomment-1108078152) you listed the fanAutoModes starting from 1-4, and in the code snippet in your [last comment](https://github.com/embee8/homebridge-panasonic-ac-platform/issues/27#issuecomment-1134230429), you check for modes 0, 2, and 3, which seems offset by 1?

**Comment by mkz212** [comment]
fanAutoMode = 2 is when both swing modes are disabled.

fanAutoMode:
1 - both enabled
2- both disabled
3 - up/down enabled and left/right disabled
4. - up/down disabled and left/right enabled

Just change this one line of code and everything will work fine.

**Comment by embee8** [comment]
What is fanMode 0 as referenced in your code snippet above?

**Comment by mkz212** [comment]
Sorry. My mistake. That is correct: 

fanAutoMode:
0 - both enabled
1 - both disabled
2 - up/down enabled and left/right disabled
3 - up/down disabled and left/right enabled

**Comment by mstendah** [comment]
Wonder if this relates to the "oscilate" setting in homekit? Seems to be difficult to get that to "off". It often returns to "on" for no obvious reason.

![image](https://user-images.githubusercontent.com/19377422/177727926-52e7f5f4-673e-4b12-b7fd-3bae26f87807.jpeg)

**Comment by mkz212** [comment]
I have the same. I have already written a solution to the problem to the author.

**Comment by mkz212** [comment]
Hi. Can we expect the fix I pointed out?

**Comment by mkz212** [comment]
Hi. When we can expect the fix I pointed out?

**Comment by embee8** [comment]
When I find the time to study and implement all related changes.

**Comment by embee8** [comment]
Not to self: Review #50 when making changes related to this functionality.

**Comment by embee8** [comment]
This feature can now be tested in the latest release.

Documentation can be found in the README and in the settings UI of the plugin.

**Comment by mkz212** [comment]
This code doesn’t work for me. In Panasonic Comfort Cloud I have both swotches enapled (Up/Down and Left/Right) but in Home app Oscilate is disabled. 


![IMG_2226](https://user-images.githubusercontent.com/82271669/232681846-2d3c1add-5516-4bd9-b669-d83b87fb5708.jpeg)
![IMG_2227](https://user-images.githubusercontent.com/82271669/232681848-04d38523-6e3c-4384-9833-9d7d518c2c7a.jpeg)
