### ISSUE TITLE
Scrape latest app version from AppStore

### ISSUE THREAD

**Issue by xyz667** [embee8/homebridge-panasonic-ac-platform#37]
> Fetching the latest version from the App Store [via API](https://developer.apple.com/documentation/appstoreconnectapi/list_all_app_store_versions_for_an_app) is a nice idea. However, the endpoint requires credentials and very likely has a rate limit. Both aspects could be managed (with some complexity), but there is no guarantee that simply using the latest available version number will be enough to keep the plugin running, because there might be additional changes in the app that we would miss.
> 
> To keep things simple and flexible, you can update the value immediately and as desired without waiting for a plugin update - see `appVersionOverride` in the advanced configuration of the settings.
> 
> I aim to bump the app version as soon as I notice it and find time. Besides that, I encourage community members to send pull requests which I am happy to review.

Hi embee8,
Fetching the latest app version does not require Apple developer access. It could be scraped off the public AppStore page:
https://apps.apple.com/de/app/panasonic-comfort-cloud/id1348640525
(note: don’t open link on idevice or you’ll be forwarded to the AppStore app and can’t see the HTML page)

_Originally posted by @xyz667 in https://github.com/embee8/homebridge-panasonic-ac-platform/issues/33#issuecomment-1193661527_

Feature request: automatically fetch the latest app version to provide to comfort cloud API.

**Comment by embee8** [comment]
This would work (for some time) but is a hacky solution. I remain sceptical for the following reasons:

1. We don't control Apple's website. If the markup changes, the process could fail. Same problem if Apple decides to block certain user agents.
2. As mentioned above, even if we stay in line with the latest version on the App Store, Panasonic could have changed more than just the version number. An automated, untested bump of the used version number could break integrations.
3. This software is free of charge and doesn't per se intend to provide the same hands-off experience as commercial software does by abstracting and absorbing the complexity of external dependencies which are out of our control. Incorporating scraping techniques would somewhat oppose the general direction of a lean, simple, and predictable design.

There have been 18 different app versions since March 2018, which averages to  ~4.5 version updates per year. If that becomes unmanageable, we should revisit this discussion.

I'll also keep an eye out for more official and stable data sources, although point 2 from above would still apply.

**Comment by xyz667** [comment]
Well, screen scraping is quite common in banking apps. Can it be considered hacky if those guys are doing it? ;-)

Will a scraper fail eventually? For sure.

If it fails, what will happen? Nothing, we would miss app updates and be dependent on manual intervention (code change or change of config). Same situation as now. 

I just think it would help many people and do no harm. Unfortunately I’m not able to provide code, however.

**Comment by embee8** [comment]
Your script provided useful direction, thanks @JurgenLB.

See #45 for an implementation of the requested feature. Let's see how well this will perform, but in my tests the solution worked without any issues, plus we still have a hard-coded value to fall back on.

**Comment by JurgenLB** [comment]
It looks very nice, a lot more dependencies though.
I'm glad my script was useful.
Together we can do more.

**Comment by embee8** [comment]
One additional dependency ([cheerio](https://github.com/cheeriojs/cheerio)), or are you referring to something else?

As per my comment above:
>Incorporating scraping techniques would somewhat oppose the general direction of a lean, simple, and predictable design.

But if it helps to prevent future app version upgrade issues, I think it's a good "return on added complexity".

**Comment by JurgenLB** [comment]
I was referring to [package-lock.json] +3000 added lines.

But nice work

**Comment by embee8** [comment]
Ah, I see. Cheerio will come with its own sub-dependencies (some overlap with already existing ones), but the number of lines in that lock file isn't a strict and accurate measure of added complexity. Its purpose is to primarily enable "_subsequent installs are able to generate identical trees, regardless of intermediate dependency updates_", see [here](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json).
